version: 1.2

workflows:
  - name: SCREEN_ANALYSIS_MODE
    subclass: WDL
    primaryDescriptorPath: /WDL/Workflows/SCREEN_ANALYSIS_MODE.wdl
  - name: SCREEN_SUBMISSION_MODE
    subclass: WDL
    primaryDescriptorPath: /WDL/Workflows/SCREEN_SUBMISSION_MODE.wdl
  - name: SCREEN_SUBMISSION_MODE_LOCAL_MSA.wdl
    subclass: WDL
    primaryDescriptorPath: /WDL/Workflows/SCREEN_SUBMISSION_MODE_LOCAL_MSA.wdl
