version: 1.2

workflows:
  - name: screen_analysis_mode
    subclass: WDL
    primaryDescriptorPath: /WDL/Workflows/screen_analysis_mode.wdl
  - name: screen_submission_mode
    subclass: WDL
    primaryDescriptorPath: /WDL/Workflows/screen_submission_mode.wdl
