version: 1.2

workflows:
  - name: Experiment_Table
    subclass: WDL
    primaryDescriptorPath: /tablet_experiment.wdl
  - name: Analyze_Table
    subclass: WDL
    primaryDescriptorPath: /WDL/Workflows/wdl_analyze_mode.wdl
  - name: Submit_Data
    subclass: WDL
    primaryDescriptorPath: /WDL/Workflows/wdl_submit_mode.wdl
  - name: Submit_Data_Test
    subclass: WDL
    primaryDescriptorPath: /WDL/Workflows/wdl_submit_mode_test.wdl
