name: protbindscreen_env
channels:
  - conda-forge
dependencies:
  - python=3.11.14
  - pip=25.2
  - pandas=2.2.3
  - numpy=2.2.6
  - scikit-learn=1.6.1
  - statsmodels=0.14.5
  - matplotlib=3.10.7
  - seaborn=0.13.2
  - plotly=6.1.1
  - pip:
      - -e /app
